### ISSUE TITLE
generate shema from a exist database

### ISSUE THREAD

**Issue by Exclamation-mark** [teocloud/teo#17]
I have a idea.

Many of our users have databases that have been running for several years. 
We are wondering if we could develop a feature similar to `teo-generate-scheme-from-db`. 
This would not only allow new projects to use `teo` without starting from scratch, 
but also provide a basic interface for older projects.

**Comment by victorteokw** [comment]
Hi @Exclamation-mark let's focus on other things first and dicuss this later. Unlike Prisma, we may not even need this.
