### ISSUE TITLE
Pipeline uppercase modifier & lowercase modifier implementation

### ISSUE THREAD

**Issue by Exclamation-mark** [teocloud/teo#2]
Can I try to implement these two pipelines? I feel that this is similar to the implementation of `Ellipsis`.

https://github.com/teocloud/teo/blob/3358ea766cdce7cfad4294a19e9ab575d49806d3/src/core/pipeline/items/string/transform/ellipsis.rs#L18-L35

**Comment by Exclamation-mark** [comment]
Is there more guidance on testing for Pipeline?

**Comment by victorteokw** [comment]
Yup please go ahead
