### ISSUE TITLE
issued the command cargo teo serve to start project, but it immediately exited without displaying any error messages.

### ISSUE THREAD

**Issue by Brandon-lz** [teocloud/teo#34]
rust version:1.75.0
when I operate by this guide:
https://teocloud.io/docs/getting-started/beginner-tutorial/write-a-schema-only-app

I use  `cargo teo serve` to start the project, but it quit quickly, just print log below:
[2024-01-23 08:02:33] sqlite connector connected for `main` at "sqlite::memory:"

I change database by postgres, and I get the same result:
[2024-01-23 07:58:23] postgres connector connected for `main` at "postgres://postgres:postgres@127.0.0.1:5432/helloteo"

**Comment by victorteokw** [comment]
Hi @Brandon-lz, which operating system you are using?

**Comment by victorteokw** [comment]
Hi @Brandon-lz, I reproduced this bug. I'm fixing it.

**Comment by victorteokw** [comment]
Hi @Brandon-lz, bug fixed
<img width="566" alt="Screenshot 2024-01-23 at 17 48 47" src="https://github.com/teocloud/teo/assets/3055936/e8719731-e75b-4388-aa0b-779a8ec4f254">
