### ISSUE TITLE
Is there a good first issue?

### ISSUE THREAD

**Issue by ruleeeer** [teocloud/teo#35]

**Comment by victorteokw** [comment]
Hi @ruleeeer , what's the problem?

**Comment by ruleeeer** [comment]
Hi, @victorteokw 
 I am interested in this project and would like to know which tasks are suitable for beginners. Based on my past experience, I usually filter by `label: good first issue`.
Does this mean there are no tasks suitable for beginners?

**Comment by victorteokw** [comment]
Hi @ruleeeer,
Since in the past, most of development work is done by myself, I seldom create issues. I will create some and assign some to you if I found it's great for starting.
