### ISSUE TITLE
Authentication and authorization Support

### ISSUE THREAD

**Issue by pwh-pwh** [teocloud/teo#47]
As a rapid development framework of this kind, I think common authentication and authorization support should be added

**Comment by victorteokw** [comment]
It used to have this feature. After the refactor of `0.0.58`, this was temporarily removed.
Currently, I'm working on this to bring this feature back. This includes **authentication**, **sessions** and **permissions**.

**Comment by victorteokw** [comment]
Hi @pwh-pwh, this is supported in 0.2.16
